# Generated by Django 4.2.7 on 2023-11-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scale_length', models.FloatField(default=25.5)),
                ('number_of_strings', models.SmallIntegerField(default=6)),
            ],
        ),
    ]
