# Generated by Django 4.2.7 on 2023-11-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarmodel',
            name='price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
