# Generated by Django 4.2.7 on 2023-11-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guitarmodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitarmodel',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='guitarmodel',
            name='manufacturer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
