# Generated by Django 4.2.7 on 2023-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_guitarmodel_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarmodel',
            name='main_img',
            field=models.ImageField(default='Default.png', upload_to='images/'),
        ),
    ]
